name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
      run: |
        if [ ${{ github.event_name }} == 'push' ] && [ ${{ github.event.ref }} == 'refs/heads/main' ]; then
          npm run deploy
        fi
