name: Build and Deploy to GKE

# TODO
on:
  push:
    branches: [main]

# These variables will be accessible in the jobs
# as ${{ env.NAME_OF_VARIABLE }}
# Note that we reference the repository secrets
# and the repository variables
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: northamerica-northeast1
  GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}
  GKE_LOCATION: ${{ vars.GKE_LOCATION }}
  IMAGE_NAME: client

jobs:
  setup-build-publish-deploy:
    # TODO: Consider renaming
    name: My [CI]CD Workflow
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # Note: By default, the code (this repository) is not checked out
    #       You need to explicitly checkout 
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SA_CICD_KEY }}

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: gke-cluster-nane1 
        location: northamerica-northeast1

    - name: List Files in Directory
      run: ls -l
     
    - name: Build Docker Image
      run: docker  build -t client:latest -f Dockerfile.client .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Tag Docker Image for GAR
      run: |
        docker tag client:latest ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/client:latest

        
    - name: Push Docker Image to Google Artifact Registry
      run: |-
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/client:latest


        
    # Push the Docker images to Google Artifact Registry
    - name: Publish
      run: |-
        echo 'TODO'

    # Deploy to GKE
    - name: Deploy
      run: |-
        echo 'TODO'
