name: Build and Deploy to GKE

# TODO
on:
  push:
    branches: [main]

# These variables will be accessible in the jobs
# as ${{ env.NAME_OF_VARIABLE }}
# Note that we reference the repository secrets
# and the repository variables
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: northamerica-northeast1
  GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}
  GKE_LOCATION: ${{ vars.GKE_LOCATION }}
  IMAGE_NAME: client

jobs:
  setup-build-publish-deploy:
    # TODO: Consider renaming
    name: My [CI]CD Workflow
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # Note: By default, the code (this repository) is not checked out
    #       You need to explicitly checkout 
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SA_CICD_KEY }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest -f mlops_module_1/Dockerfile.client mlops_module_1

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        
    # Push the Docker images to Google Artifact Registry
    - name: Publish
      run: |-
        echo 'TODO'

    # Deploy to GKE
    - name: Deploy
      run: |-
        echo 'TODO'
